version: 2
jobs:
  setup_app:
    docker:
      - image: circleci/node:10.18.1
    steps:
      - checkout
      - run:
          name: Start app
          command: yarn dev

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup_app
