version: 2.1
jobs:
  start_app:
    docker:
      - image: selenium/standalone-chrome
    steps:
      - checkout
      - run:
          name: Install client side dependencies
          command: cd client && yarn install
      - run:
          name: Install server side dependencies
          command: yarn install
      - run:
          name: Run client unit tests
          command: cd client && yarn test src/__tests__/unit/**
      - run:
          name: Start app
          command: yarn dev
          background: true
      - run:
          name: Run E2E tests
          command: yarn server:start && cd client && yarn wdio:run -l "silent"
workflows:
  version: 2
  build_and_test:
    jobs:
      - start_app:
          pre-steps:

